name: minerl
channels:
  - pytorch
  - conda-forge
  - defaults
channel_priority: true
dependencies:
  - python=3.7
  - pip
  - py-opencv
  - cudatoolkit=11.1
  - pytorch=1.9.0
  - pip:
    - crowdai_api
    - minerl
    - coloredlogs
    - matplotlib
    - pyro4
    - numpy
